//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogicResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogicResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend.Logic.LogicResources", typeof(LogicResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.
        /// </summary>
        internal static string CctiCategory {
            get {
                return ResourceManager.GetString("CctiCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios de TI.
        /// </summary>
        internal static string CctiClass {
            get {
                return ResourceManager.GetString("CctiClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacaciones.
        /// </summary>
        internal static string CctiType {
            get {
                return ResourceManager.GetString("CctiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itbs123!.
        /// </summary>
        internal static string CsmPassword {
            get {
                return ResourceManager.GetString("CsmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wsConnect40121.
        /// </summary>
        internal static string CsmUsername {
            get {
                return ResourceManager.GetString("CsmUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ct.html.
        /// </summary>
        internal static string CtFile {
            get {
                return ResourceManager.GetString("CtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cv.html.
        /// </summary>
        internal static string CvFile {
            get {
                return ResourceManager.GetString("CvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdf.
        /// </summary>
        internal static string DocumentsOutPutFormat {
            get {
                return ResourceManager.GetString("DocumentsOutPutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\xampp\htdocs\temp\documentos\.
        /// </summary>
        internal static string DocumentsUrl {
            get {
                return ResourceManager.GetString("DocumentsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to experiencia-laboral.html.
        /// </summary>
        internal static string ExperienciaLaboralTemplate {
            get {
                return ResourceManager.GetString("ExperienciaLaboralTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formacion-academica.html.
        /// </summary>
        internal static string FormacionAcademicaTemplate {
            get {
                return ResourceManager.GetString("FormacionAcademicaTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formacion-profesional.html.
        /// </summary>
        internal static string FormacionProfesionalTemplate {
            get {
                return ResourceManager.GetString("FormacionProfesionalTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\xampp\htdocs\temp\fotos\.
        /// </summary>
        internal static string FotosURL {
            get {
                return ResourceManager.GetString("FotosURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proyectos.html.
        /// </summary>
        internal static string ProyectosTemplate {
            get {
                return ResourceManager.GetString("ProyectosTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string ResponseFormat {
            get {
                return ResourceManager.GetString("ResponseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\xampp\htdocs\temp\templates\.
        /// </summary>
        internal static string TemplatesURL {
            get {
                return ResourceManager.GetString("TemplatesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ticket_identifier.
        /// </summary>
        internal static string TicketIdentifier {
            get {
                return ResourceManager.GetString("TicketIdentifier", resourceCulture);
            }
        }
    }
}
