//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public System.DateTime Ano_Finalizacion { get; set; }
    
        public virtual User User { get; set; }
    }
}
