//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExprecienciaLaboral
    {
        public int Id { get; set; }
        public System.DateTime Ano_Inicio { get; set; }
        public string Desempeno { get; set; }
        public Nullable<System.DateTime> Ano_Finalizacion { get; set; }
        public string Empresa { get; set; }
        public string Descripcion { get; set; }
    
        public virtual User User { get; set; }
    }
}
