//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelbackupContainer : DbContext
    {
        public ModelbackupContainer()
            : base("name=ModelbackupContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificado> CertificadoSet { get; set; }
        public virtual DbSet<Curso> CursosSet { get; set; }
        public virtual DbSet<Estudio> EstudioSet { get; set; }
        public virtual DbSet<ExprecienciaLaboral> ExprecienciaLaboralSet { get; set; }
        public virtual DbSet<SolicitudVacaciones> SolicitudVacacionesSet { get; set; }
        public virtual DbSet<Rol> RolSet1 { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Proyectos> ProyectosSet { get; set; }
    }
}
