//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sncargo
    {
        public sncargo()
        {
            this.sncargo1 = new HashSet<sncargo>();
            this.snemple = new HashSet<snemple>();
        }
    
        public string co_cargo { get; set; }
        public string des_cargo { get; set; }
        public string co_ocupacion { get; set; }
        public string co_depart { get; set; }
        public string depende_de { get; set; }
        public bool direcc_confianza { get; set; }
        public decimal sueldo_sug { get; set; }
        public int num_trab_sug { get; set; }
        public string func_general { get; set; }
        public string func_especifica { get; set; }
        public string requisitos { get; set; }
        public string comentarios { get; set; }
        public string riesgo { get; set; }
        public string clasif_riesgo { get; set; }
        public string lesiones { get; set; }
        public string prevenciones { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string trasnfe { get; set; }
        public string revisado { get; set; }
        public byte[] validador { get; set; }
    
        public virtual ICollection<sncargo> sncargo1 { get; set; }
        public virtual sncargo sncargo2 { get; set; }
        public virtual ICollection<snemple> snemple { get; set; }
    }
}
