//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class snemple
    {
        public snemple()
        {
            this.snemple1 = new HashSet<snemple>();
        }
    
        public string cod_emp { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string ci { get; set; }
        public string pasaporte { get; set; }
        public string rif { get; set; }
        public string lib_militar { get; set; }
        public string profesion { get; set; }
        public int nivel_acad { get; set; }
        public int nac { get; set; }
        public string sexo { get; set; }
        public string edo_civ { get; set; }
        public string correo_e { get; set; }
        public string status { get; set; }
        public string co_cont { get; set; }
        public System.DateTime fecha_nac { get; set; }
        public string lugar_nac { get; set; }
        public System.DateTime fecha_ing { get; set; }
        public Nullable<System.DateTime> fecha_egr { get; set; }
        public string tip_egr { get; set; }
        public string motivo { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string co_depart { get; set; }
        public string co_ubicacion { get; set; }
        public string co_ban { get; set; }
        public string co_cargo { get; set; }
        public byte[] foto { get; set; }
        public string des_foto { get; set; }
        public string cta_banc { get; set; }
        public string dis_cen { get; set; }
        public string cod_cta { get; set; }
        public string co_ingr { get; set; }
        public string cod_ben { get; set; }
        public string cod_caja { get; set; }
        public string forma_pag { get; set; }
        public string cod_suc { get; set; }
        public string avisar_a { get; set; }
        public string telf_contact { get; set; }
        public string dir_contact { get; set; }
        public string cod_candi { get; set; }
        public string carnet { get; set; }
        public string supervisor { get; set; }
        public bool sindicalizado { get; set; }
        public bool uniformes { get; set; }
        public bool vehiculo { get; set; }
        public string talla_zap { get; set; }
        public string talla_pant { get; set; }
        public string talla_camisa { get; set; }
        public string talla_casco { get; set; }
        public string talla_otro1 { get; set; }
        public string talla_otro2 { get; set; }
        public string licencia { get; set; }
        public Nullable<int> grado_lic { get; set; }
        public string co_ban1 { get; set; }
        public string cta_banc1 { get; set; }
        public Nullable<System.DateTime> cta_fecing1 { get; set; }
        public string tipo_cta1 { get; set; }
        public string co_ban2 { get; set; }
        public string cta_banc2 { get; set; }
        public Nullable<System.DateTime> cta_fecing2 { get; set; }
        public string tipo_cta2 { get; set; }
        public string co_ban3 { get; set; }
        public string cta_banc3 { get; set; }
        public Nullable<System.DateTime> cta_fecing3 { get; set; }
        public string tipo_cta3 { get; set; }
        public string co_ban4 { get; set; }
        public string cta_banc4 { get; set; }
        public Nullable<System.DateTime> cta_fecing4 { get; set; }
        public string cod_empresa { get; set; }
        public bool fuero_sindic { get; set; }
        public decimal peso { get; set; }
        public decimal estatura { get; set; }
        public bool zurdo { get; set; }
        public string grupo_sang { get; set; }
        public string alergico_a { get; set; }
        public string enfermedades { get; set; }
        public bool discapacitado { get; set; }
        public string co_cert { get; set; }
        public string clasificacion { get; set; }
        public string tratamiento { get; set; }
        public Nullable<System.DateTime> fecha_exp { get; set; }
        public Nullable<System.DateTime> fecha_venc { get; set; }
        public string tipo_discapac { get; set; }
        public string observaciones { get; set; }
        public string co_asegurado { get; set; }
        public string condicion { get; set; }
        public bool rep_segindust { get; set; }
        public string co_repsegind { get; set; }
        public int tipo_mintra { get; set; }
        public string ocupacion { get; set; }
        public string cert_aptitud { get; set; }
        public string perm_menor { get; set; }
        public string estado { get; set; }
        public string municipio { get; set; }
        public string parroquia { get; set; }
        public string ubicacion { get; set; }
        public string tipo_cont { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_us_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string trasnfe { get; set; }
        public string revisado { get; set; }
        public byte[] validador { get; set; }
        public string nombre_completo { get; set; }
    
        public virtual ICollection<snemple> snemple1 { get; set; }
        public virtual snemple snemple2 { get; set; }
        public virtual sncargo sncargo { get; set; }
    }
}
