//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Estudio = new HashSet<Estudio>();
            this.ExprecienciaLaboral = new HashSet<ExprecienciaLaboral>();
            this.Certificado = new HashSet<Certificado>();
            this.Curso = new HashSet<Curso>();
            this.SolicitudVacaciones = new HashSet<SolicitudVacaciones>();
        }
    
        public string Correo { get; set; }
        public string ModeloVehiculo { get; set; }
        public string ColorVehiculo { get; set; }
        public string AnoVehiculo { get; set; }
        public string PlacaVehiculo { get; set; }
        public string Usename { get; set; }
        public string Foto { get; set; }
        public string CorreoPersonal { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<Estudio> Estudio { get; set; }
        public virtual ICollection<ExprecienciaLaboral> ExprecienciaLaboral { get; set; }
        public virtual ICollection<Certificado> Certificado { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
        public virtual ICollection<SolicitudVacaciones> SolicitudVacaciones { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
