//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.IntranetException {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend.IntranetException.ExceptionResource", typeof(ExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error tratando de obtener el status de la solicitud de vacaciones.
        /// </summary>
        internal static string CsmTicketError {
            get {
                return ResourceManager.GetString("CsmTicketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La duracion de la solicitud debe ser mayor a 0.
        /// </summary>
        internal static string DuracionErronea {
            get {
                return ResourceManager.GetString("DuracionErronea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ususario no existe, verifique el correo electronico.
        /// </summary>
        internal static string EmpleadoInexistente {
            get {
                return ResourceManager.GetString("EmpleadoInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no ha ingresado a itbs en la fecha de inicio de la solicitud, por favor ingrese otra fecha.
        /// </summary>
        internal static string FechaDeInicioErronea {
            get {
                return ResourceManager.GetString("FechaDeInicioErronea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio es un dia feriado, por favor ingrese otra fecha.
        /// </summary>
        internal static string FechaDeInicioEsUnDiaFeriado {
            get {
                return ResourceManager.GetString("FechaDeInicioEsUnDiaFeriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio es un dia de un fin de semana, por favor ingrese otra fecha.
        /// </summary>
        internal static string FechaDeInicioEsUnFinDeSemana {
            get {
                return ResourceManager.GetString("FechaDeInicioEsUnFinDeSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio debe ser mayor que la fecha actual, por favor ingrese otra fecha.
        /// </summary>
        internal static string FechaDeInicioMenorQueFechaActual {
            get {
                return ResourceManager.GetString("FechaDeInicioMenorQueFechaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Rol que ingreso es invalido.
        /// </summary>
        internal static string RolInexistente {
            get {
                return ResourceManager.GetString("RolInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol debe ser obligatorio.
        /// </summary>
        internal static string RolInvalido {
            get {
                return ResourceManager.GetString("RolInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La direccion de correo electronico de Itbs que ingreso ya esta en uso.
        /// </summary>
        internal static string UsuarioExistente {
            get {
                return ResourceManager.GetString("UsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ususario no existe, verifique sus credenciales.
        /// </summary>
        internal static string UsuarioInexistente {
            get {
                return ResourceManager.GetString("UsuarioInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo de usuario no se encuentra en uso por ningun usuario de Profit.
        /// </summary>
        internal static string UsuarioInexistenteProfit {
            get {
                return ResourceManager.GetString("UsuarioInexistenteProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario debe ser obligatorio.
        /// </summary>
        internal static string UsuarioInvalido {
            get {
                return ResourceManager.GetString("UsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de dias que usted dispone es menor que la solicitada.
        /// </summary>
        internal static string UsuarioNoDisponeDeDias {
            get {
                return ResourceManager.GetString("UsuarioNoDisponeDeDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene no tiene un año dentro de itbs.
        /// </summary>
        internal static string UsuarioNoPuedeSolicitarVacaciones {
            get {
                return ResourceManager.GetString("UsuarioNoPuedeSolicitarVacaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ya posee una solicitud de vacaciones abiertas, Comuniquese con su supervisor para actualizar el status.
        /// </summary>
        internal static string UsuarioTieneSolicitudAbierta {
            get {
                return ResourceManager.GetString("UsuarioTieneSolicitudAbierta", resourceCulture);
            }
        }
    }
}
