//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet_Backend.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class itbsEntities : DbContext
    {
        public itbsEntities()
            : base("name=itbsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Certificado> CertificadoSet { get; set; }
        public DbSet<Curso> CursosSet { get; set; }
        public DbSet<Estudio> EstudioSet { get; set; }
        public DbSet<ExprecienciaLaboral> ExprecienciaLaboralSet { get; set; }
        public DbSet<SolicitudVacaciones> SolicitudVacacionesSet { get; set; }
        public DbSet<Rol> RolSet1 { get; set; }
        public DbSet<User> UserSet { get; set; }
    }
}
